language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

install:
  - composer install

script: 
  - cd tests
  - php -S localhost:8080 -t server & 
  - phpunit --bootstrap bootstrap.php src/WebRequestTest.php 

